trigger: none
pr: none

# schedules:
#   - cron: "0 17 * * *"
#     displayName: Weekly Cleanup
#     branches:
#       include:
#         - master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo "Hello, World!"
  displayName: Hello World