trigger: none
pr: none

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self

- bash: |
    echo "Before running script"
    pwd
    ls -lah
    ls -lah scripts
  displayName: 'List files before execution'

- bash: |
    chmod +x scripts/check-expired-secrets.sh
  displayName: 'Make script executable'

- task: AzureCLI@2
  displayName: 'Check expired App Registration secrets'
  inputs:
    azureSubscription: 'Strategic Platform - non-live'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '$(Build.SourcesDirectory)/scripts/check-expired-secrets.sh'

- bash: |
    echo "After running script"
    pwd
    ls -lah
    echo ""
    echo "Scripts directory:"
    ls -lah scripts || true
    echo ""
    echo "Looking for expired.txt:"
    find . -name "expired.txt" -type f
  displayName: 'List files after execution'

- task: AzureCLI@2
  displayName: 'Deleting expired App Registration secrets'
  inputs:
    azureSubscription: 'Strategic Platform - non-live'
    scriptType: 'bash'
    scriptLocation: 'scriptPath'
    scriptPath: '$(Build.SourcesDirectory)/scripts/delete-expired-secrets.sh'